  main = ".open-next/worker.js"
  name = "blog-hopperlowe"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

  [env.preview.vars]
  NEXT_PUBLIC_BASE_URL = "http://localhost:8787"

  [env.production.vars]
  NEXT_PUBLIC_BASE_URL = "https://blog-hopperlowe.rhopperlowe.workers.dev"